---
title: "maps"
author: "Mark Stephens"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(readxl)
library(janitor)
library(gt)

census_api_key("5442782eaca8626cf6e2db4721acf67182afa9fb")

```


```{r, include=FALSE}

racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")

harris <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "TX",
                  county = "Harris County",
                  geometry = TRUE,
                  summary_var = "B02001_001")

marin <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "CA",
                  county = "Marin County",
                  geometry = TRUE,
                  summary_var = "B02001_001")

sf <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "CA",
                  county = "San Francisco County",
                  geometry = TRUE,
                  summary_var = "B02001_001")


sf %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = Percent, color = Percent)) +
  facet_wrap(~ variable) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of San Francisco County, California",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()

```

